[package]
name = "lib-switch-operate"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
anyhow = "1.0"
tokio-serial = "5.4"
tokio-modbus = "0.16"
num_enum = "0.7"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
serde_json = "1.0"